### PR TITLE
⚠️ CONFLICT! Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request: CONFLICT #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-aws-lambda.git`](https://github.com/cisagov/skeleton-aws-lambda.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/findings-data-import-lambda.git findings-data-import-lambda
    cd findings-data-import-lambda
    git remote add skeleton https://github.com/cisagov/skeleton-aws-lambda.git
    git remote set-url --push skeleton no_push
    git switch develop
    git checkout -b lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git checkout --ours -- .github/lineage.yml
    git add .github/lineage.yml
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the branch,
   `commit`, and `push` your changes:

    ```console
    git add .coveragerc .github/CODEOWNERS .github/workflows/build.yml .gitignore .isort.cfg CONTRIBUTING.md Dockerfile README.md build.sh bump_version.sh docker-compose.yml eal/_version.py fdi/_version.py lambda_handler.py setup.py src/example/_version.py 
    git commit --message="Resolve Lineage conflicts."
    git push --force --set-upstream origin lineage/skeleton
    ```

1. Wait for all the automated tests to pass.

1. Check the "Everything is cool" checkbox below:

    - [x] ✌️ The conflicts in this pull request have been resolved.

1. Mark this draft pull request "Ready for review".

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Review by jsf9k — CHANGES_REQUESTED** [review]
The `setup.py` still lists support for 3.6, 3.7, and 3.8.  I think that either `setup.py` should be constrained to support 3.8 only, or this repo should use the python version matrix jazz to test all three versions.

In short, `setup.py` and the `build.yml` workflow do not agree with each other.

**Comment by mcdonnnj** [comment]
> 
> 
> The `setup.py` still lists support for 3.6, 3.7, and 3.8. I think that either `setup.py` should be constrained to support 3.8 only, or this repo should use the python version matrix jazz to test all three versions.
> 
> In short, `setup.py` and the `build.yml` workflow do not agree with each other.

This PR is unrelated to https://github.com/cisagov/skeleton-aws-lambda/pull/10. I'm not sure why it took a PR generating in [cisagov/skeleton-aws-lambda](https://github.com/cisagov/skeleton-aws-lambda) for this to generate, but this PR consisted of all the changes I'd already handled in #19.

**Comment by jsf9k** [comment]
> This PR is unrelated to [cisagov/skeleton-aws-lambda#10](https://github.com/cisagov/skeleton-aws-lambda/pull/10). I'm not sure why it took a PR generating in [cisagov/skeleton-aws-lambda](https://github.com/cisagov/skeleton-aws-lambda) for this to generate, but this PR consisted of all the changes I'd already handled in #19.

I think I'm missing something.  I don't see how the concerns in my comment have been addressed.  TBH, I don't understand "this PR consisted of all the changes I'd already handled in #19."  (This sounds harsher than intended, but I don't know how to reword it.  I am confused.)

**Comment by jsf9k** [comment]
> > This PR is unrelated to [cisagov/skeleton-aws-lambda#10](https://github.com/cisagov/skeleton-aws-lambda/pull/10). I'm not sure why it took a PR generating in [cisagov/skeleton-aws-lambda](https://github.com/cisagov/skeleton-aws-lambda) for this to generate, but this PR consisted of all the changes I'd already handled in #19.
> 
> I think I'm missing something. I don't see how the concerns in my comment have been addressed. TBH, I don't understand "this PR consisted of all the changes I'd already handled in #19." (This sounds harsher than intended, but I don't know how to reword it. I am confused.)

@mcdonnnj explained to me that this repo will get a second PR via lineage once cisagov/skeleton-aws-lambda#10 is merged.

**Review by jsf9k — APPROVED** [review]

**Comment by mcdonnnj** [comment]
> 
> 
> > This PR is unrelated to [cisagov/skeleton-aws-lambda#10](https://github.com/cisagov/skeleton-aws-lambda/pull/10). I'm not sure why it took a PR generating in [cisagov/skeleton-aws-lambda](https://github.com/cisagov/skeleton-aws-lambda) for this to generate, but this PR consisted of all the changes I'd already handled in #19.
> 
> I think I'm missing something. I don't see how the concerns in my comment have been addressed. TBH, I don't understand "this PR consisted of all the changes I'd already handled in #19." (This sounds harsher than intended, but I don't know how to reword it. I am confused.)

EDIT: Added this reply to hopefully provide clarity to what I meant.

Sorry for not being clear enough. What I meant is that this auto-generated PR was repeating the work I did in #19 in an attempt to avoid this exact situation. It is unclear to me right now why `lineage` did not generate this PR before now, and why it appears the generated PR https://github.com/cisagov/skeleton-aws-lambda/pull/10 triggered `lineage` to decide this repository wasn't up-to-date.

**Review by dav3r — APPROVED** [review]
👍 👍

**Review by mcdonnnj — APPROVED** [review]
Good work @mcdonnnj :godmode:

**Pull request merged**
