### PR TITLE
Remove line that was added by mistake

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull requests a harmless but unnecessary line that was added for testing purposes in #59.

## 💭 Motivation and context ##

This change was thought to be reverted in #59 but was somehow not.

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]

**Comment by dv4harr10** [comment]
Hi Team, the CODEOWNERS file has a message that says 'file contains errors'. line 6 appears to be incorrect.

**Comment by jsf9k** [comment]
> Hi Team, the CODEOWNERS file has a message that says 'file contains errors'. line 6 appears to be incorrect.

Where do you see that?  Can you provide a link?

**Comment by dv4harr10** [comment]
https://github.com/cisagov/findings-data-import-lambda/blob/bugfix/remove-line/.github/CODEOWNERS

**Comment by jsf9k** [comment]
> https://github.com/cisagov/findings-data-import-lambda/blob/bugfix/remove-line/.github/CODEOWNERS

Interesting.  It looks like [@Yablargo removed himself from the cisagov organization](https://github.com/organizations/cisagov/settings/audit-log?q=actor%3AYablargo+) back in May, yet he is the primary owner for the code in this repository.

What should we do here?  Do the other members of @cisagov/team-ois have any thoughts?

**Comment by dav3r** [comment]
> > https://github.com/cisagov/findings-data-import-lambda/blob/bugfix/remove-line/.github/CODEOWNERS
> 
> Interesting. It looks like [@Yablargo removed himself from the cisagov organization](https://github.com/organizations/cisagov/settings/audit-log?q=actor%3AYablargo+) back in May, yet he is the primary owner for the code in this repository.
> 
> What should we do here? Do the other members of @cisagov/team-ois have any thoughts?

We should probably contact someone else on that team to pick up ownership of this repo, at least until it is no longer in use and can be archived.

**Comment by jsf9k** [comment]
> https://github.com/cisagov/findings-data-import-lambda/blob/bugfix/remove-line/.github/CODEOWNERS

I'm trying to identify a new codeowner (or codeowners) for this repo, and tracking that in #67.  In the meantime, the issue with the `CODEOWNERS` file should not stop this PR from moving forward.

**Review by dv4harr10 — APPROVED** [review]

**Comment by jsf9k** [comment]
> Hi Team, the CODEOWNERS file has a message that says 'file contains errors'. line 6 appears to be incorrect.

Thanks for pointing that out @dv4harr10.  I completely missed it.

**Pull request merged**
