### PR TITLE
Making Logging Great Again

### PR DESCRIPTION
**Pull request by mcdonnnj**
# 

## 🗣 Description
This small PR is focused on making logging more informative when records are skipped and end results for a particular uploaded object.

Some code is also DRYed for moving S3 objects after processing is finished or if there is an error.

## 💭 Motivation and Context
Previously there was only a summary logged after processing an uploaded JSON. These changes make it clear why a record was skipped and for which file the logging output pertains.

The code to move files after processing or in the event of an error is almost identical and so it was moved into a function with necessary parameters to cut down on code duplication.

## 🧪 Testing
I tested this in my testing workspace and verified that log output was as expected.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Looks great to me!

**Review by mzack5020 — APPROVED** [review]
Love it (and the PR name)! Thanks @mcdonnnj

**Review by felddy — APPROVED** [review]
Nooice!  🐃 ❄️

**Review by dav3r — APPROVED** [review]
All aces here boss! 🉑

**Pull request merged**
