### PR TITLE
#5 Multi-Line Build Instructions

### PR DESCRIPTION
**Pull request by mzack5020**
Edited README.md so that build instructions for AWS zip file are multi-line and not individual code lines.

### CODE REVIEW

**Comment by mzack5020** [comment]
Small change per issue #5

**Review by dav3r — APPROVED** [review]
👍 👍

**Review by jsf9k — APPROVED** [review]
:+1:

**Review by mcdonnnj — APPROVED** [review]
Thanks for the work. 👍

**Comment by mzack5020** [comment]
Thanks all for your review.

**Pull request merged**
